const PDFDocument = require("pdfkit-table");
const ExcelJS = require("exceljs");
const path = require("path");
const fs = require("fs");
const { chromium } = require("playwright");
const { sendEmail } = require("../../utils/mailer");
const { renderTemplate } = require("../../utils/templateRenderer");

const sanitizeAttachmentFileName = (value, fallback = "report.pdf") => {
  const safe = String(value || fallback)
    .replace(/[\\/:*?"<>|]+/g, "_")
    .replace(/\s+/g, "_")
    .replace(/^_+|_+$/g, "");

  return safe || fallback;
};

const fileToDataUri = (filePath) => {
  if (!fs.existsSync(filePath)) return "";
  const ext = path.extname(filePath).slice(1).toLowerCase();
  const mimeType =
    ext === "png" ? "image/png" :
    ext === "jpg" || ext === "jpeg" ? "image/jpeg" :
    ext === "svg" ? "image/svg+xml" :
    "application/octet-stream";
  const content = fs.readFileSync(filePath).toString("base64");
  return `data:${mimeType};base64,${content}`;
};

const CBS_LOGO_PATH = path.join(__dirname, "..", "..", "..", "assets", "images", "ui", "logo_koperasi_cbs.png");
const REVORA_LOGO_PATH = path.join(__dirname, "..", "..", "..", "assets", "images", "ui", "logo_horizontal.png");
const CBS_LOGO_URI = fileToDataUri(CBS_LOGO_PATH);
const REVORA_LOGO_URI = fileToDataUri(REVORA_LOGO_PATH);

const escapeHtml = (value) =>
  String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");

const buildReportPdfFromHtml = async (html) => {
  const normalizedHtml = String(html || "")
    .replace(
      /(<img\b[^>]*class="[^"]*\bbrand-logo-cbs\b[^"]*"[^>]*src=")[^"]*(")/gi,
      `$1${CBS_LOGO_URI}$2`
    )
    .replace(
      /(<img\b[^>]*class="[^"]*\bbrand-logo-revora\b[^"]*"[^>]*src=")[^"]*(")/gi,
      `$1${REVORA_LOGO_URI}$2`
    );

  const browser = await chromium.launch({
    headless: true,
  });

  try {
    const page = await browser.newPage({
      viewport: { width: 1440, height: 2200 },
    });
    await page.setContent(normalizedHtml, { waitUntil: "networkidle" });
    return await page.pdf({
      format: "A4",
      printBackground: true,
      margin: {
        top: "18mm",
        right: "16mm",
        bottom: "18mm",
        left: "16mm",
      },
    });
  } finally {
    await browser.close();
  }
};

const buildEmailPdfHtml = ({
  title,
  subtitle,
  generatedAt,
  generatedBy,
  meta,
  columns,
  rows,
}) => {
  const metaItems = [
    { label: "Generated At", value: generatedAt || new Date().toISOString() },
    ...(generatedBy ? [{ label: "Generated By", value: generatedBy }] : []),
    ...(meta || []),
  ];

  const renderMeta = metaItems
    .map(
      (item) => `
        <div class="meta-item">
          <div class="meta-label">${escapeHtml(item.label)}</div>
          <div class="meta-value">${escapeHtml(item.value)}</div>
        </div>
      `
    )
    .join("");

  const headerCells = columns
    .map((column) => `<th>${escapeHtml(column.title)}</th>`)
    .join("");
  const bodyRows = rows
    .map(
      (row) => `
        <tr>
          ${columns
            .map((column) => `<td>${escapeHtml(row[column.key] ?? "-")}</td>`)
            .join("")}
        </tr>
      `
    )
    .join("");

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <style>
      * { box-sizing: border-box; }
      body {
        margin: 0;
        color: #0f172a;
        font-family: Arial, Helvetica, sans-serif;
        font-size: 12px;
        line-height: 1.45;
        background: #ffffff;
      }
      .page { padding: 18mm 16mm; }
      .report-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 24px;
        border-bottom: 2px solid #0f172a;
        padding-bottom: 12px;
        margin-bottom: 14px;
      }
      .brand-logos { display: flex; align-items: center; gap: 10px; }
      .brand-logo-cbs { width: 52px; height: 52px; object-fit: contain; }
      .brand-logo-revora { width: 190px; height: 44px; object-fit: contain; }
      .report-title { font-size: 20px; font-weight: 800; text-align: right; }
      .report-subtitle { color: #475569; text-align: right; margin-top: 2px; }
      .meta-grid {
        display: grid;
        grid-template-columns: repeat(3, minmax(0, 1fr));
        gap: 8px;
        margin: 10px 0 12px;
      }
      .meta-item {
        border: 1px solid #cbd5e1;
        padding: 6px 8px;
        min-height: 38px;
      }
      .meta-label {
        color: #64748b;
        font-size: 10px;
        font-weight: 700;
        text-transform: uppercase;
      }
      .meta-value {
        margin-top: 3px;
        font-weight: 700;
        word-break: break-word;
      }
      table { width: 100%; border-collapse: collapse; table-layout: fixed; }
      th, td {
        border: 1px solid #cbd5e1;
        padding: 7px 8px;
        vertical-align: top;
        overflow-wrap: anywhere;
        word-break: break-word;
        white-space: pre-line;
      }
      th {
        background: #e2e8f0;
        color: #0f172a;
        font-size: 11px;
        font-weight: 800;
        text-transform: uppercase;
      }
      tbody tr:nth-child(even) { background: #f8fafc; }
      .footer {
        border-top: 1px solid #cbd5e1;
        color: #64748b;
        font-size: 10px;
        margin-top: 18px;
        padding-top: 8px;
        text-align: right;
      }
    </style>
  </head>
  <body>
    <main class="page">
      <header class="report-header">
        <div class="brand-logos">
          ${CBS_LOGO_URI ? `<img class="brand-logo-cbs" src="${CBS_LOGO_URI}" alt="CBS" />` : ""}
          ${REVORA_LOGO_URI ? `<img class="brand-logo-revora" src="${REVORA_LOGO_URI}" alt="Revora" />` : ""}
        </div>
        <div>
          <div class="report-title">${escapeHtml(title)}</div>
          ${subtitle ? `<div class="report-subtitle">${escapeHtml(subtitle)}</div>` : ""}
        </div>
      </header>
      <section class="meta-grid">
        ${renderMeta}
      </section>
      <table>
        <thead>
          <tr>${headerCells}</tr>
        </thead>
        <tbody>${bodyRows}</tbody>
      </table>
      <footer class="footer">Generated by CBS Revora</footer>
    </main>
  </body>
</html>`;
};

const buildExcelBuffer = async (title, columns, rows, meta) => {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet("Report");
  let currentRow = 1;

  // Add Title
  worksheet.getCell(`A${currentRow}`).value = title;
  worksheet.getCell(`A${currentRow}`).font = { size: 16, bold: true };
  currentRow += 2;

  // Add Meta
  if (meta && meta.length > 0) {
    meta.forEach((m) => {
      worksheet.getCell(`A${currentRow}`).value = m.label;
      worksheet.getCell(`A${currentRow}`).font = { bold: true };
      worksheet.getCell(`B${currentRow}`).value = m.value;
      currentRow++;
    });
    currentRow++;
  }

  // Add Headers
  worksheet.getRow(currentRow).values = columns.map(c => c.title);
  worksheet.getRow(currentRow).font = { bold: true };
  worksheet.getRow(currentRow).alignment = { horizontal: 'center' };
  columns.forEach((c, i) => {
    worksheet.getColumn(i + 1).width = Math.max(c.title.length + 5, 15);
  });
  currentRow++;

  // Add Rows
  rows.forEach((row) => {
    const rowValues = columns.map(c => {
      const val = row[c.key];
      return val !== null && val !== undefined ? val : "-";
    });
    worksheet.getRow(currentRow).values = rowValues;
    currentRow++;
  });

  return await workbook.xlsx.writeBuffer();
};

const buildPdfBuffer = async (title, columns, rows, meta) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: "A4" });
    const buffers = [];
    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => resolve(Buffer.concat(buffers)));
    doc.on("error", reject);

    const logoCbsPath = path.join(__dirname, "..", "..", "..", "assets", "images", "ui", "logo_koperasi_cbs.png");
    const logoRevoraPath = path.join(__dirname, "..", "..", "..", "assets", "images", "ui", "logo_horizontal.png");

    // Header
    if (fs.existsSync(logoCbsPath)) doc.image(logoCbsPath, 40, 30, { width: 50 });
    if (fs.existsSync(logoRevoraPath)) doc.image(logoRevoraPath, 100, 42, { width: 70 });
    doc.fillColor("#0f172a").fontSize(18).font("Helvetica-Bold").text(title.toUpperCase(), 200, 35, { align: "right" });
    doc.fillColor("#64748b").fontSize(10).font("Helvetica").text("Koperasi Citra Bina Sejahtera", 200, 58, { align: "right" });
    doc.moveTo(40, 90).lineTo(555, 90).strokeColor("#cbd5e1").lineWidth(1).stroke();
    doc.moveDown(2);

    // Meta
    doc.y = 110;
    if (meta && meta.length > 0) {
      doc.fillColor("#1e293b").fontSize(9);
      let metaX = 40, metaY = 110;
      meta.forEach((m, i) => {
        doc.font("Helvetica-Bold").text(`${m.label}: `, metaX, metaY, { continued: true }).font("Helvetica").text(String(m.value));
        if (i % 2 === 1) { metaY += 14; metaX = 40; } else { metaX = 300; }
      });
      doc.moveDown(2);
    }

    // Table
    const tableData = {
      headers: columns.map((c) => c.title),
      rows: rows.map((row) => columns.map((c) => (row[c.key] !== null && row[c.key] !== undefined ? String(row[c.key]) : "-"))),
    };
    doc.table(tableData, {
      prepareHeader: () => doc.font("Helvetica-Bold").fontSize(10).fillColor("#0f172a"),
      prepareRow: () => doc.font("Helvetica").fontSize(9).fillColor("#334155"),
      padding: 5,
    });
    doc.end();
  });
};

const sendEmailReport = async (req, res) => {
  const { recipient_email, subject, message, format, title, columns, rows, meta, generated_by, pdf_base64, pdf_filename } = req.body;

  if (!recipient_email || !format) {
    return res.status(400).json({ message: "recipient_email and format are required." });
  }

  if (!pdf_base64 && (!columns || !rows)) {
    return res.status(400).json({ message: "columns and rows are required when no PDF attachment is provided." });
  }

  try {
    let attachmentBuffer, filename, contentType;
    if (format === "EXCEL") {
      attachmentBuffer = await buildExcelBuffer(title || "Report", columns, rows, meta);
      filename = `${(title || "report").toLowerCase().replace(/\s+/g, "_")}_${Date.now()}.xlsx`;
      contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    } else if (pdf_base64) {
      attachmentBuffer = Buffer.from(pdf_base64, "base64");
      filename = sanitizeAttachmentFileName(pdf_filename, `${(title || "report").toLowerCase().replace(/\s+/g, "_")}_${Date.now()}.pdf`);
      contentType = "application/pdf";
    } else if (req.body.print_html) {
      attachmentBuffer = await buildReportPdfFromHtml(req.body.print_html);
      filename = sanitizeAttachmentFileName(
        pdf_filename,
        `${(title || "report").toLowerCase().replace(/\s+/g, "_")}_${Date.now()}.pdf`
      );
      contentType = "application/pdf";
    } else {
      const html = req.body.print_html
        ? req.body.print_html
        : buildEmailPdfHtml({
            title: title || "Report",
            subtitle: "Generated report",
            generatedAt: new Date().toISOString(),
            generatedBy: generated_by,
            meta,
            columns,
            rows,
          });
      attachmentBuffer = await buildReportPdfFromHtml(html);
      filename = `${(title || "report").toLowerCase().replace(/\s+/g, "_")}_${Date.now()}.pdf`;
      contentType = "application/pdf";
    }

    const html = renderTemplate("ReportEmail", {
      TITLE: "Data Report Generated",
      RECIPIENT_NAME: req.body.recipient_name || recipient_email.split("@")[0],
      REPORT_NAME: title || "Data Report",
      MESSAGE: message || "Please find the attached report file for the requested data.",
    });

    const logoPath = path.join(__dirname, "..", "..", "..", "assets", "images", "ui", "logo_horizontal.png");
    await sendEmail({
      to: recipient_email,
      subject: subject || title || "Data Report",
      html,
      attachments: [
        { filename, content: attachmentBuffer, contentType },
        { filename: "logo.png", path: logoPath, cid: "revora-logo" },
      ],
    });

    res.json({ message: "Email sent successfully." });
  } catch (error) {
    console.error("Email error:", error);
    res.status(500).json({ message: "Failed to send email.", error: error.message });
  }
};

module.exports = { sendEmailReport };
