INSERT INTO tbl_shu_periods (
    id_shu_period,
    period_name,
    start_date,
    end_date,
    total_cooperative_income,
    total_member_spending,
    gross_profit_display,
    sales_income_amount,
    sales_cost_amount,
    sales_net_amount,
    sales_manager_cut_amount,
    sales_shu_pool_amount,
    business_income_amount,
    business_expense_amount,
    business_net_amount,
    business_manager_cut_amount,
    business_shu_pool_amount,
    total_shu_distributed_amount,
    total_manager_fund_amount,
    reconciliation_gap_amount,
    calculation_status,
    notes,
    is_active,
    created_date,
    created_by
) VALUES
    (
        '7d0553de-6f59-4ac8-88ad-50a78de74044',
        'SHU 2025-2026',
        '2025-12-01',
        '2026-11-30',
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        'DRAFT',
        'Current SHU period.',
        'Y',
        '2026-02-01 10:00:00',
        '34305b6c-c61f-4247-b2c2-d6ec35a4b2bc'
    ),
    (
        '88888888-8888-4888-8888-888888888888',
        'SHU 2024-2025',
        '2024-12-01',
        '2025-11-30',
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        'DRAFT',
        'Historical SHU period ready for calculation testing.',
        'Y',
        '2025-12-01 10:00:00',
        '34305b6c-c61f-4247-b2c2-d6ec35a4b2bc'
    )
ON CONFLICT (period_name) DO UPDATE SET
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    total_cooperative_income = EXCLUDED.total_cooperative_income,
    total_member_spending = EXCLUDED.total_member_spending,
    gross_profit_display = EXCLUDED.gross_profit_display,
    sales_income_amount = EXCLUDED.sales_income_amount,
    sales_cost_amount = EXCLUDED.sales_cost_amount,
    sales_net_amount = EXCLUDED.sales_net_amount,
    sales_manager_cut_amount = EXCLUDED.sales_manager_cut_amount,
    sales_shu_pool_amount = EXCLUDED.sales_shu_pool_amount,
    business_income_amount = EXCLUDED.business_income_amount,
    business_expense_amount = EXCLUDED.business_expense_amount,
    business_net_amount = EXCLUDED.business_net_amount,
    business_manager_cut_amount = EXCLUDED.business_manager_cut_amount,
    business_shu_pool_amount = EXCLUDED.business_shu_pool_amount,
    total_shu_distributed_amount = EXCLUDED.total_shu_distributed_amount,
    total_manager_fund_amount = EXCLUDED.total_manager_fund_amount,
    reconciliation_gap_amount = EXCLUDED.reconciliation_gap_amount,
    calculation_status = EXCLUDED.calculation_status,
    notes = EXCLUDED.notes,
    is_active = EXCLUDED.is_active,
    created_by = EXCLUDED.created_by;
