INSERT INTO tbl_shu_periods (
    id_shu_period,
    period_name,
    start_date,
    end_date,
    total_cooperative_income,
    total_member_spending,
    gross_profit_display,
    income_belanja_amount,
    expense_belanja_amount,
    net_belanja_amount,
    manager_cut_belanja_amount,
    shu_belanja_pool_amount,
    income_usaha_amount,
    expense_usaha_amount,
    net_usaha_amount,
    manager_cut_usaha_amount,
    shu_usaha_pool_amount,
    total_shu_distributed_amount,
    total_manager_fund_amount,
    reconciliation_gap_amount,
    calculation_status,
    notes,
    is_active,
    created_date,
    created_by
) VALUES
    (
        '7d0553de-6f59-4ac8-88ad-50a78de74044',
        'SHU 2025-2026',
        '2025-12-01',
        '2026-11-30',
        2330000.00,
        30000.00,
        2154000.00,
        30000.00,
        0.00,
        30000.00,
        3000.00,
        27000.00,
        2300000.00,
        176000.00,
        2124000.00,
        212400.00,
        1911600.00,
        1938600.00,
        215400.00,
        0.00,
        'CALCULATED',
        'Seed SHU period based on seeded POS and external financial entries.',
        'Y',
        '2026-02-01 10:00:00',
        '34305b6c-c61f-4247-b2c2-d6ec35a4b2bc'
    )
ON CONFLICT (period_name) DO UPDATE SET
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    total_cooperative_income = EXCLUDED.total_cooperative_income,
    total_member_spending = EXCLUDED.total_member_spending,
    gross_profit_display = EXCLUDED.gross_profit_display,
    income_belanja_amount = EXCLUDED.income_belanja_amount,
    expense_belanja_amount = EXCLUDED.expense_belanja_amount,
    net_belanja_amount = EXCLUDED.net_belanja_amount,
    manager_cut_belanja_amount = EXCLUDED.manager_cut_belanja_amount,
    shu_belanja_pool_amount = EXCLUDED.shu_belanja_pool_amount,
    income_usaha_amount = EXCLUDED.income_usaha_amount,
    expense_usaha_amount = EXCLUDED.expense_usaha_amount,
    net_usaha_amount = EXCLUDED.net_usaha_amount,
    manager_cut_usaha_amount = EXCLUDED.manager_cut_usaha_amount,
    shu_usaha_pool_amount = EXCLUDED.shu_usaha_pool_amount,
    total_shu_distributed_amount = EXCLUDED.total_shu_distributed_amount,
    total_manager_fund_amount = EXCLUDED.total_manager_fund_amount,
    reconciliation_gap_amount = EXCLUDED.reconciliation_gap_amount,
    calculation_status = EXCLUDED.calculation_status,
    notes = EXCLUDED.notes,
    is_active = EXCLUDED.is_active,
    created_by = EXCLUDED.created_by;
