const ExcelJS = require("exceljs");
const path = require("path");
const fs = require("fs");
const { chromium } = require("playwright");

const sanitizeAttachmentFileName = (value, fallback = "report.pdf") => {
  const safe = String(value || fallback)
    .replace(/[\\/:*?"<>|]+/g, "_")
    .replace(/\s+/g, "_")
    .replace(/^_+|_+$/g, "");

  return safe || fallback;
};

const fileToDataUri = (filePath) => {
  if (!fs.existsSync(filePath)) return "";
  const ext = path.extname(filePath).slice(1).toLowerCase();
  const mimeType =
    ext === "png" ? "image/png" :
    ext === "jpg" || ext === "jpeg" ? "image/jpeg" :
    ext === "svg" ? "image/svg+xml" :
    "application/octet-stream";
  const content = fs.readFileSync(filePath).toString("base64");
  return `data:${mimeType};base64,${content}`;
};

const CBS_LOGO_PATH = path.join(__dirname, "..", "..", "assets", "images", "ui", "logo_koperasi_cbs.png");
const REVORA_LOGO_PATH = path.join(__dirname, "..", "..", "assets", "images", "ui", "logo_horizontal.png");
const CBS_LOGO_URI = fileToDataUri(CBS_LOGO_PATH);
const REVORA_LOGO_URI = fileToDataUri(REVORA_LOGO_PATH);

const escapeHtml = (value) =>
  String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");

const buildReportPdfFromHtml = async (html) => {
  const normalizedHtml = String(html || "")
    .replace(
      /(<img\b[^>]*class="[^"]*\bbrand-logo-cbs\b[^"]*"[^>]*src=")[^"]*(")/gi,
      `$1${CBS_LOGO_URI}$2`
    )
    .replace(
      /(<img\b[^>]*class="[^"]*\bbrand-logo-revora\b[^"]*"[^>]*src=")[^"]*(")/gi,
      `$1${REVORA_LOGO_URI}$2`
    );

  const browser = await chromium.launch({
    headless: true,
  });

  try {
    const page = await browser.newPage({
      viewport: { width: 1440, height: 2200 },
    });
    await page.setContent(normalizedHtml, { waitUntil: "networkidle" });
    return await page.pdf({
      format: "A4",
      printBackground: true,
      margin: {
        top: "18mm",
        right: "16mm",
        bottom: "18mm",
        left: "16mm",
      },
    });
  } finally {
    await browser.close();
  }
};

const formatDateTime = (date) => {
  if (!date) return "-";
  const d = new Date(date);
  const pad = (n) => String(n).padStart(2, "0");

  const day = pad(d.getDate());
  const month = pad(d.getMonth() + 1);
  const year = d.getFullYear();
  const hours = pad(d.getHours());
  const minutes = pad(d.getMinutes());
  const seconds = pad(d.getSeconds());

  return `${day}/${month}/${year}, ${hours}:${minutes}:${seconds}`;
};

const buildEmailPdfHtml = ({
  title,
  subtitle,
  generatedAt,
  generatedBy,
  meta,
  columns,
  rows,
}) => {
  const metaItems = [
    { label: "Generated At", value: generatedAt || formatDateTime(new Date()) },
    ...(generatedBy ? [{ label: "Generated By", value: generatedBy }] : []),
    ...(meta || []),
  ];

  const renderMeta = metaItems
    .map(
      (item) => `
        <div class="meta-item">
          <div class="meta-label">${escapeHtml(item.label)}</div>
          <div class="meta-value">${escapeHtml(item.value)}</div>
        </div>
      `
    )
    .join("");

  const headerCells = columns
    .map((column) => `<th>${escapeHtml(column.title)}</th>`)
    .join("");
  const bodyRows = rows
    .map(
      (row) => `
        <tr>
          ${columns
            .map((column) => `<td>${escapeHtml(row[column.key] ?? "-")}</td>`)
            .join("")}
        </tr>
      `
    )
    .join("");

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <style>
      * { box-sizing: border-box; }
      body {
        margin: 0;
        color: #0f172a;
        font-family: Arial, Helvetica, sans-serif;
        font-size: 12px;
        line-height: 1.45;
        background: #ffffff;
      }
      .page { padding: 18mm 16mm; }
      .report-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 24px;
        border-bottom: 2px solid #0f172a;
        padding-bottom: 12px;
        margin-bottom: 14px;
      }
      .brand-logos { display: flex; align-items: center; gap: 10px; }
      .brand-logo-cbs { width: 52px; height: 52px; object-fit: contain; }
      .brand-logo-revora { width: 190px; height: 44px; object-fit: contain; }
      .report-title { font-size: 20px; font-weight: 800; text-align: right; }
      .report-subtitle { color: #475569; text-align: right; margin-top: 2px; }
      .meta-grid {
        display: grid;
        grid-template-columns: repeat(3, minmax(0, 1fr));
        gap: 8px;
        margin: 10px 0 12px;
      }
      .meta-item {
        border: 1px solid #cbd5e1;
        padding: 6px 8px;
        min-height: 38px;
      }
      .meta-label {
        color: #64748b;
        font-size: 10px;
        font-weight: 700;
        text-transform: uppercase;
      }
      .meta-value {
        margin-top: 3px;
        font-weight: 700;
        word-break: break-word;
      }
      table { width: 100%; border-collapse: collapse; table-layout: fixed; }
      th, td {
        border: 1px solid #cbd5e1;
        padding: 7px 8px;
        vertical-align: top;
        overflow-wrap: anywhere;
        word-break: break-word;
        white-space: pre-line;
      }
      th {
        background: #e2e8f0;
        color: #0f172a;
        font-size: 11px;
        font-weight: 800;
        text-transform: uppercase;
      }
      tbody tr:nth-child(even) { background: #f8fafc; }
      .footer {
        border-top: 1px solid #cbd5e1;
        color: #64748b;
        font-size: 10px;
        margin-top: 18px;
        padding-top: 8px;
        text-align: right;
      }
    </style>
  </head>
  <body>
    <main class="page">
      <header class="report-header">
        <div class="brand-logos">
          ${CBS_LOGO_URI ? `<img class="brand-logo-cbs" src="${CBS_LOGO_URI}" alt="CBS" />` : ""}
          ${REVORA_LOGO_URI ? `<img class="brand-logo-revora" src="${REVORA_LOGO_URI}" alt="Revora" />` : ""}
        </div>
        <div>
          <div class="report-title">${escapeHtml(title)}</div>
          ${subtitle ? `<div class="report-subtitle">${escapeHtml(subtitle)}</div>` : ""}
        </div>
      </header>
      <section class="meta-grid">
        ${renderMeta}
      </section>
      <table>
        <thead>
          <tr>${headerCells}</tr>
        </thead>
        <tbody>${bodyRows}</tbody>
      </table>
      <footer class="footer">Generated by CBS Revora</footer>
    </main>
  </body>
</html>`;
};

const buildExcelBuffer = async (title, subtitle, columns, rows, meta) => {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet("Report");
  workbook.creator = "CBS Revora";
  workbook.created = new Date();
  let currentRow = 1;

  const safeColumns = Array.isArray(columns) ? columns : [];
  const safeRows = Array.isArray(rows) ? rows : [];
  const columnCount = Math.max(safeColumns.length, 1);

  if (fs.existsSync(CBS_LOGO_PATH)) {
    const cbsLogoId = workbook.addImage({ filename: CBS_LOGO_PATH, extension: "png" });
    worksheet.addImage(cbsLogoId, { tl: { col: 0, row: 0 }, ext: { width: 52, height: 52 } });
  }
  if (fs.existsSync(REVORA_LOGO_PATH)) {
    const revoraLogoId = workbook.addImage({ filename: REVORA_LOGO_PATH, extension: "png" });
    worksheet.addImage(revoraLogoId, { tl: { col: 1, row: 0.15 }, ext: { width: 190, height: 44 } });
  }

  worksheet.mergeCells(1, Math.max(columnCount - 2, 1), 1, columnCount);
  worksheet.mergeCells(2, Math.max(columnCount - 2, 1), 2, columnCount);
  worksheet.getCell(1, Math.max(columnCount - 2, 1)).value = title || "Report";
  worksheet.getCell(1, Math.max(columnCount - 2, 1)).font = { size: 20, bold: true, color: { argb: "FF0F2852" } };
  worksheet.getCell(1, Math.max(columnCount - 2, 1)).alignment = { horizontal: "right", vertical: "middle" };
  if (subtitle) {
    worksheet.getCell(2, Math.max(columnCount - 2, 1)).value = subtitle;
    worksheet.getCell(2, Math.max(columnCount - 2, 1)).font = { size: 11, color: { argb: "FF475569" } };
    worksheet.getCell(2, Math.max(columnCount - 2, 1)).alignment = { horizontal: "right", vertical: "middle" };
  }
  worksheet.getRow(1).height = 28;
  worksheet.getRow(2).height = 22;
  currentRow = 4;

  // Add Meta
  const metaItems = Array.isArray(meta) ? meta : [];
  if (metaItems.length > 0) {
    metaItems.forEach((m) => {
      worksheet.getCell(`A${currentRow}`).value = m.label;
      worksheet.getCell(`A${currentRow}`).font = { bold: true, color: { argb: "FF334155" } };
      worksheet.getCell(`A${currentRow}`).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFEAF0F7" } };
      worksheet.getCell(`B${currentRow}`).value = m.value ?? "-";
      if (columnCount > 2) worksheet.mergeCells(currentRow, 2, currentRow, columnCount);
      currentRow++;
    });
    currentRow++;
  }

  // Check if this is a sectioned report
  const isSectioned = safeRows.some(r => r._type === "section_title");

  // Add Headers (only if not sectioned)
  if (!isSectioned) {
    const headerRow = worksheet.getRow(currentRow);
    safeColumns.forEach((c, i) => {
      const cell = headerRow.getCell(i + 1);
      cell.value = c.title;
      cell.font = { bold: true, color: { argb: "FF0F172A" } };
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFD9E2F3" } };
      cell.alignment = { horizontal: c.align || "left", vertical: "middle" };
      cell.border = {
        top: { style: "thin", color: { argb: "FFB7C4D4" } },
        left: { style: "thin", color: { argb: "FFB7C4D4" } },
        bottom: { style: "thin", color: { argb: "FFB7C4D4" } },
        right: { style: "thin", color: { argb: "FFB7C4D4" } },
      };
      worksheet.getColumn(i + 1).width = Number(c.width) || Math.max(String(c.title || "").length + 5, 15);
    });
    currentRow++;
  } else {
    // Apply column widths for sectioned report
    safeColumns.forEach((c, i) => {
      worksheet.getColumn(i + 1).width = Number(c.width) || 18;
    });
  }

  // Add Rows
  safeRows.forEach((row, rowIndex) => {
    const excelRow = worksheet.getRow(currentRow);
    const rowType = row._type; // e.g. "section_title", "section_header", "section_empty", "data", "blank"

    if (rowType === "blank" || Object.keys(row).filter(k => k !== "_type").length === 0) {
      excelRow.height = 10;
      currentRow++;
      return;
    }

    if (rowType === "section_title") {
      let sectionCols = columnCount;
      const nextRow = safeRows[rowIndex + 1];
      if (nextRow && nextRow._type === "section_header") {
        sectionCols = Object.keys(nextRow).filter(k => k !== "_type").length;
      }

      const cell = excelRow.getCell(1);
      cell.value = row[safeColumns[0]?.key || "col_1"];
      cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F2852" } };
      cell.alignment = { horizontal: "left", vertical: "middle" };
      worksheet.mergeCells(currentRow, 1, currentRow, Math.max(sectionCols, 1));
      currentRow++;
      return;
    }

    if (rowType === "section_empty") {
      let sectionCols = columnCount;
      const prevRow = safeRows[rowIndex - 1];
      if (prevRow && prevRow._type === "section_header") {
        sectionCols = Object.keys(prevRow).filter(k => k !== "_type").length;
      }

      const cell = excelRow.getCell(1);
      cell.value = row[safeColumns[0]?.key || "col_1"];
      cell.font = { italic: true, color: { argb: "FF64748B" } };
      worksheet.mergeCells(currentRow, 1, currentRow, Math.max(sectionCols, 1));
      currentRow++;
      return;
    }

    safeColumns.forEach((c, i) => {
      const val = row[c.key];
      const cell = excelRow.getCell(i + 1);
      
      const hasKey = Object.prototype.hasOwnProperty.call(row, c.key);

      if (rowType === "section_header") {
        if (hasKey && val) {
          cell.value = val;
          cell.font = { bold: true, color: { argb: "FF0F172A" } };
          cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFD9E2F3" } };
          cell.alignment = { horizontal: c.align || "left", vertical: "middle" };
          cell.border = {
            top: { style: "thin", color: { argb: "FFB7C4D4" } },
            left: { style: "thin", color: { argb: "FFB7C4D4" } },
            bottom: { style: "thin", color: { argb: "FFB7C4D4" } },
            right: { style: "thin", color: { argb: "FFB7C4D4" } },
          };
        }
      } else {
        // Normal data row
        if (hasKey) {
          cell.value = val !== null && val !== undefined && val !== "" ? val : "-";
          cell.alignment = { horizontal: c.align || "left", vertical: "top", wrapText: true };
          if (typeof val === "number") cell.numFmt = "#,##0";
          cell.border = {
            top: { style: "thin", color: { argb: "FFB7C4D4" } },
            left: { style: "thin", color: { argb: "FFB7C4D4" } },
            bottom: { style: "thin", color: { argb: "FFB7C4D4" } },
            right: { style: "thin", color: { argb: "FFB7C4D4" } },
          };
        }
      }
    });
    currentRow++;
  });

  return await workbook.xlsx.writeBuffer();
};

module.exports = {
  sanitizeAttachmentFileName,
  buildReportPdfFromHtml,
  buildEmailPdfHtml,
  buildExcelBuffer,
  escapeHtml,
};
