import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f3f6fb" },
  content: { padding: 14, gap: 12 },
  headerRow: { gap: 4 },
  pageTitle: { fontSize: 30, color: "#0f2852", fontWeight: "800" },
  subTitle: { color: "#64748b", fontSize: 13 },
  actionRow: { flexDirection: "row", gap: 10 },
  finalizeActionWrap: { position: "relative", gap: 5, maxWidth: 360 },
  actionTooltip: {
    position: "absolute",
    bottom: 46,
    left: 102,
    width: 330,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#fde68a",
    backgroundColor: "#fffbeb",
    paddingHorizontal: 10,
    paddingVertical: 8,
    zIndex: 1000,
    elevation: 24,
  },
  actionTooltipText: { color: "#92400e", fontSize: 12, lineHeight: 17 },
  button: { height: 40, borderRadius: 10, paddingHorizontal: 14, alignItems: "center", justifyContent: "center" },
  exportIconButton: { width: 40, height: 40, borderRadius: 10, borderWidth: 1, borderColor: "#bfdbfe", backgroundColor: "#eff6ff", alignItems: "center", justifyContent: "center" },
  buttonGhost: { borderWidth: 1, borderColor: "#cbd5e1", backgroundColor: "#fff" },
  buttonPrimary: { backgroundColor: "#1d4ed8" },
  buttonWarn: { backgroundColor: "#b45309" },
  buttonSuccess: { backgroundColor: "#16a34a" },
  buttonMuted: { backgroundColor: "#94a3b8" },
  buttonDisabled: { opacity: 0.72 },
  buttonGhostText: { color: "#334155", fontWeight: "700" },
  buttonPrimaryText: { color: "#fff", fontWeight: "700" },
  buttonWarnText: { color: "#fff", fontWeight: "700" },
  buttonSuccessText: { color: "#fff", fontWeight: "700" },
  stateWrap: { minHeight: 90, alignItems: "center", justifyContent: "center", gap: 8 },
  stateText: { color: "#64748b" },
  errorText: { color: "#dc2626", fontWeight: "600" },
  successText: { color: "#166534", fontWeight: "600" },
  card: { backgroundColor: "#fff", borderRadius: 14, borderWidth: 1, borderColor: "#dbe3ee", padding: 14, gap: 10 },
  cardTitle: { color: "#0f2852", fontSize: 18, fontWeight: "800" },
  periodHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  statusBadge: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  statusDraft: { backgroundColor: "#e2e8f0" },
  statusCalculated: { backgroundColor: "#dbeafe" },
  statusFinalized: { backgroundColor: "#dcfce7" },
  statusText: { fontSize: 11, fontWeight: "800", color: "#0f172a" },
  statusLine: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
  metaText: { color: "#64748b", fontSize: 13 },
  finalizedNotice: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#bbf7d0",
    backgroundColor: "#f0fdf4",
    color: "#166534",
    fontSize: 12,
    lineHeight: 17,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  summaryGrid: { gap: 8 },
  summaryItem: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "#f8fbff",
  },
  summaryLabel: { color: "#475569", fontSize: 12, marginBottom: 3 },
  summaryValue: { color: "#0f2852", fontSize: 15, fontWeight: "700" },
  pathRow: { flexDirection: "row", gap: 10, marginTop: 2 },
  pathCard: { flex: 1, borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 10, padding: 10, backgroundColor: "#ffffff" },
  pathTitle: { fontWeight: "800", color: "#1e3a8a", marginBottom: 6, fontSize: 13 },
  pathLine: { color: "#334155", fontSize: 12, marginBottom: 2 },
  rowCell: { fontSize: 12, color: "#0f172a" },
  row: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: "#eef2f7" },
  rowName: { color: "#0f2852", fontWeight: "700", fontSize: 14 },
  rowMeta: { color: "#64748b", fontSize: 12, marginTop: 2 },
  rowAmount: { color: "#0f2852", fontWeight: "800", fontSize: 14 },
  modalOverlay: { flex: 1, backgroundColor: "rgba(15,23,42,0.4)", justifyContent: "center", padding: 14 },
  modalCard: { backgroundColor: "#fff", borderRadius: 14, borderWidth: 1, borderColor: "#dbe3ee", padding: 12, maxHeight: "85%" },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  tableHeadRow: { backgroundColor: "#f8fbff", borderTopLeftRadius: 12, borderTopRightRadius: 12 },
  tableBody: { maxHeight: 420 },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#eef2f7" },
  tableHeadCell: { color: "#334155", fontWeight: "800", fontSize: 12, paddingHorizontal: 8, paddingVertical: 10 },
  tableCell: { color: "#0f172a", fontSize: 12, paddingHorizontal: 8, paddingVertical: 10 },
  colName: { width: 220 },
  colAmount: { width: 140 },
  colPercent: { width: 90 },
  colFlag: { width: 90 },
  inlineActionButton: { height: 32, paddingHorizontal: 10, borderRadius: 8 },
  modalTitle: { color: "#0f172a", fontSize: 18, fontWeight: "800", marginBottom: 4 },
  detailScroll: { maxHeight: "86%" },
  detailScrollContent: { gap: 10, paddingBottom: 6 },
  closeBtn: { marginTop: 6, minHeight: 36, borderRadius: 10, backgroundColor: "#1d4ed8", alignItems: "center", justifyContent: "center" },
  closeBtnText: { color: "#fff", fontSize: 13, fontWeight: "700" },
  exportWrap: { position: "relative" },
  detailPrintButton: { minHeight: 36, borderRadius: 10, borderWidth: 1, borderColor: "#bfdbfe", backgroundColor: "#eff6ff", paddingHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 },
  detailPrintButtonText: { color: "#1d4ed8", fontSize: 12, fontWeight: "700" },
  exportMenu: {
    position: "absolute",
    top: 36,
    right: 0,
    borderWidth: 1,
    borderColor: "#dbe3ee",
    backgroundColor: "#fff",
    borderRadius: 10,
    minWidth: 120,
    zIndex: 50,
    elevation: 8,
  },
  exportMenuItem: { paddingHorizontal: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "#eef2f7" },
  exportMenuText: { color: "#0f172a", fontSize: 13, fontWeight: "700" },
  filterLabel: { color: "#334155", fontSize: 12, fontWeight: "700" },
  rangeRow: { flexDirection: "row", gap: 8 },
  rangeInput: {
    flex: 1,
    height: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    color: "#0f172a",
  },
});
