import { Platform } from "react-native";
import { Asset } from "expo-asset";
import { fetchWithAuth } from "./fetchWithAuth";
import { buildExportFileName, sanitizeFileNamePart } from "./exportFileName";

export type ExcelValue = string | number | boolean | Date | null | undefined;

export type ExcelMetaItem = {
  label: string;
  value: ExcelValue;
};

export type ExcelColumn<Row> = {
  key: string;
  title: string;
  width?: number;
  align?: "left" | "center" | "right";
  getValue: (row: Row, index: number) => ExcelValue;
};

export type ExcelTableOptions<Row> = {
  title: string;
  subtitle?: string;
  reportKey: string;
  rows: Row[];
  columns: ExcelColumn<Row>[];
  generatedAt?: string | Date;
  generatedBy?: string | null;
  meta?: ExcelMetaItem[];
  fileName?: string;
  logoUris?: {
    cbs?: string;
    revora?: string;
  };
};

export type ExcelSection = {
  title: string;
  columns: {
    key: string;
    title: string;
    width?: number;
    align?: "left" | "center" | "right";
  }[];
  rows: Record<string, ExcelValue>[];
};

export type ExcelSectionWorkbookOptions = {
  title: string;
  subtitle?: string;
  reportKey: string;
  generatedAt?: string | Date;
  generatedBy?: string | null;
  meta?: ExcelMetaItem[];
  sections: ExcelSection[];
  fileName?: string;
};

const CBS_LOGO = require("../assets/images/ui/logo_koperasi_cbs.png");
const REVORA_LOGO = require("../assets/images/ui/logo_horizontal.png");

const getAssetUri = (asset: unknown) => {
  if (typeof asset === "number") {
    return Asset.fromModule(asset).uri || "";
  }

  if (asset && typeof asset === "object" && "uri" in asset && typeof (asset as { uri?: unknown }).uri === "string") {
    return (asset as { uri: string }).uri;
  }

  return "";
};

const blobToDataUri = (blob: Blob) =>
  new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(typeof reader.result === "string" ? reader.result : "");
    reader.onerror = () => reject(reader.error || new Error("Failed to read asset."));
    reader.readAsDataURL(blob);
  });

const assetToDataUri = async (asset: unknown) => {
  const uri = getAssetUri(asset);
  if (!uri) return "";
  if (uri.startsWith("data:")) return uri;

  if (Platform.OS !== "web") {
    return uri;
  }

  try {
    const response = await fetch(uri);
    if (!response.ok) return uri;
    const blob = await response.blob();
    return await blobToDataUri(blob);
  } catch {
    return uri;
  }
};

const assetToArrayBuffer = async (asset: unknown) => {
  const uri = getAssetUri(asset);
  if (!uri) return null;

  try {
    const response = await fetch(uri);
    if (!response.ok) return null;
    return await response.arrayBuffer();
  } catch {
    return null;
  }
};

const escapeHtml = (value: ExcelValue) =>
  String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");

const formatDateTime = (value?: string | Date | null) => {
  const date = value instanceof Date ? value : value ? new Date(value) : new Date();
  if (Number.isNaN(date.getTime())) return String(value || "-");

  return new Intl.DateTimeFormat("id-ID", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  })
    .format(date)
    .replace(/\./g, ":");
};

const formatValue = (value: ExcelValue) => {
  if (value instanceof Date) return formatDateTime(value);
  if (typeof value === "boolean") return value ? "Yes" : "No";
  if (value === null || value === undefined || value === "") return "-";
  return String(value);
};

const alignmentStyle = (align?: "left" | "center" | "right") => {
  if (align === "center") return "text-align:center;";
  if (align === "right") return "text-align:right;";
  return "text-align:left;";
};

const renderMetaRows = (items: ExcelMetaItem[], columnCount: number) => {
  if (items.length === 0) return "";

  return items
    .map(
      (item) => `
        <tr>
          <td class="meta-label">${escapeHtml(item.label)}</td>
          <td class="meta-value" colspan="${Math.max(columnCount - 1, 1)}">${escapeHtml(formatValue(item.value))}</td>
        </tr>
      `
    )
    .join("");
};

export const buildExcelTableHtml = <Row,>({
  title,
  subtitle,
  rows,
  columns,
  generatedAt = new Date(),
  generatedBy,
  meta = [],
  logoUris,
}: ExcelTableOptions<Row>) => {
  const columnCount = Math.max(columns.length, 1);
  const allMeta = [
    { label: "Generated At", value: formatDateTime(generatedAt) },
    ...(generatedBy ? [{ label: "Generated By", value: generatedBy }] : []),
    { label: "Total Rows", value: rows.length },
    ...meta,
  ];
  const cbsLogoUri = logoUris?.cbs ?? getAssetUri(CBS_LOGO);
  const revoraLogoUri = logoUris?.revora ?? getAssetUri(REVORA_LOGO);
  const colgroup = columns.map((column) => `<col style="width:${column.width || 18}ch" />`).join("");

  return `<!doctype html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
  <head>
    <meta charset="utf-8" />
    <!--[if gte mso 9]>
    <xml>
      <x:ExcelWorkbook>
        <x:ExcelWorksheets>
          <x:ExcelWorksheet>
            <x:Name>${escapeHtml(title.slice(0, 31))}</x:Name>
            <x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions>
          </x:ExcelWorksheet>
        </x:ExcelWorksheets>
      </x:ExcelWorkbook>
    </xml>
    <![endif]-->
    <style>
      table { border-collapse: collapse; font-family: Arial, sans-serif; font-size: 11pt; }
      td, th { border: 1px solid #b7c4d4; padding: 6px 8px; vertical-align: middle; }
      .no-border { border: 0; }
      .title { font-size: 18pt; font-weight: 700; color: #0f2852; text-align: right; border: 0; }
      .subtitle { font-size: 10pt; color: #475569; text-align: right; border: 0; }
      .meta-label { background: #eaf0f7; color: #475569; font-weight: 700; text-transform: uppercase; }
      .meta-value { font-weight: 700; }
      .header-cell { background: #dbe5f1; font-weight: 700; color: #0f172a; text-transform: uppercase; }
      .number { mso-number-format:"\\#\\,\\#\\#0"; }
      .text { mso-number-format:"\\@"; }
    </style>
  </head>
  <body>
    <table>
      <colgroup>${colgroup}</colgroup>
      <tr>
        <td class="no-border" colspan="${Math.max(Math.floor(columnCount / 2), 1)}">
          ${cbsLogoUri ? `<img src="${escapeHtml(cbsLogoUri)}" width="52" height="52" />` : ""}
          ${revoraLogoUri ? `<img src="${escapeHtml(revoraLogoUri)}" width="190" height="44" />` : ""}
        </td>
        <td class="title" colspan="${Math.max(columnCount - Math.max(Math.floor(columnCount / 2), 1), 1)}">${escapeHtml(title)}</td>
      </tr>
      ${subtitle ? `<tr><td class="no-border" colspan="${Math.max(Math.floor(columnCount / 2), 1)}"></td><td class="subtitle" colspan="${Math.max(columnCount - Math.max(Math.floor(columnCount / 2), 1), 1)}">${escapeHtml(subtitle)}</td></tr>` : ""}
      <tr><td class="no-border" colspan="${columnCount}"></td></tr>
      ${renderMetaRows(allMeta, columnCount)}
      <tr><td class="no-border" colspan="${columnCount}"></td></tr>
      <tr>
        ${columns.map((column) => `<th class="header-cell" style="${alignmentStyle(column.align)}">${escapeHtml(column.title)}</th>`).join("")}
      </tr>
      ${rows
        .map(
          (row, rowIndex) => `
            <tr>
              ${columns
                .map((column) => {
                  const value = column.getValue(row, rowIndex);
                  const className = typeof value === "number" ? "number" : "text";
                  return `<td class="${className}" style="${alignmentStyle(column.align)}">${escapeHtml(formatValue(value))}</td>`;
                })
                .join("")}
            </tr>
          `
        )
        .join("")}
    </table>
  </body>
</html>`;
};

export const buildExcelTableHtmlWithEmbeddedLogos = async <Row,>(options: ExcelTableOptions<Row>) => {
  const cbsLogoUri = await assetToDataUri(CBS_LOGO);
  const revoraLogoUri = await assetToDataUri(REVORA_LOGO);
  return buildExcelTableHtml({
    ...options,
    logoUris: {
      cbs: cbsLogoUri,
      revora: revoraLogoUri,
    },
  });
};

export const buildExcelFileName = (reportKey: string, date?: string | Date | null) =>
  buildExportFileName({
    prefix: ["cbs-revora", reportKey].map(sanitizeFileNamePart).filter(Boolean).join("-") || "cbs-revora-report",
    date,
    extension: "xlsx",
  });

export const downloadExcelHtml = (html: string, fileName: string) => {
  if (Platform.OS !== "web") {
    throw new Error("Excel export is currently available on web only.");
  }

  if (typeof document === "undefined" || typeof URL === "undefined") {
    throw new Error("Excel export is not available in this environment.");
  }

  const blob = new Blob([html], {
    type: "application/vnd.ms-excel;charset=utf-8",
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

const downloadWorkbookBuffer = (buffer: BlobPart, fileName: string) => {
  if (Platform.OS !== "web") {
    throw new Error("Excel export is currently available on web only.");
  }

  if (typeof document === "undefined" || typeof URL === "undefined") {
    throw new Error("Excel export is not available in this environment.");
  }

  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

const assertWebExcelExport = () => {
  if (Platform.OS !== "web") {
    throw new Error("Excel export is currently available on web only.");
  }

  if (typeof document === "undefined" || typeof URL === "undefined") {
    throw new Error("Excel export is not available in this environment.");
  }
};

const loadExcelJs = async () => {
  assertWebExcelExport();
  const module = await import("exceljs");
  return module.default || module;
};

const loadNativeFileExportModules = async () => {
  const fileSystemModule = await import("expo-file-system");
  return {
    Directory: fileSystemModule.Directory,
    File: fileSystemModule.File,
  };
};

const splitFileName = (fileName: string) => {
  const dotIndex = fileName.lastIndexOf(".");
  if (dotIndex <= 0) {
    return { name: fileName, extension: "" };
  }

  return {
    name: fileName.slice(0, dotIndex),
    extension: fileName.slice(dotIndex),
  };
};

const getAvailableFileName = (
  directory: Awaited<ReturnType<typeof loadNativeFileExportModules>>["Directory"]["prototype"],
  fileName: string
) => {
  const existingNames = new Set(directory.list().map((item) => item.name));
  if (!existingNames.has(fileName)) {
    return fileName;
  }

  const { name, extension } = splitFileName(fileName);
  for (let index = 1; index < 1000; index += 1) {
    const candidate = `${name} (${index})${extension}`;
    if (!existingNames.has(candidate)) {
      return candidate;
    }
  }

  return `${name}-${Date.now()}${extension}`;
};

const downloadBackendExcel = async ({
  title,
  reportKey,
  generatedAt,
  generatedBy,
  meta = [],
  columns,
  rows,
  fileName,
}: {
  title: string;
  reportKey: string;
  generatedAt?: string | Date;
  generatedBy?: string | null;
  meta?: ExcelMetaItem[];
  columns: { key: string; title: string; width?: number; align?: "left" | "center" | "right" }[];
  rows: Record<string, ExcelValue>[];
  fileName?: string;
}) => {
  if (Platform.OS === "web") return false;

  const targetFileName = fileName || buildExcelFileName(reportKey, generatedAt);
  const response = await fetchWithAuth(`/api/reports/export-excel`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      title,
      file_name: targetFileName,
      columns,
      rows,
      meta: [
        ...(!meta.some(m => m.label === "Generated At") ? [{ label: "Generated At", value: formatDateTime(generatedAt) }] : []),
        ...(generatedBy && !meta.some(m => m.label === "Generated By") ? [{ label: "Generated By", value: generatedBy }] : []),
        ...(!meta.some(m => m.label === "Total Rows") ? [{ label: "Total Rows", value: rows.length }] : []),
        ...meta,
      ],
    }),
  });

  if (!response.ok) {
    const payload = await response.json().catch(() => null);
    throw new Error(payload?.message || "Failed to export Excel.");
  }

  const fileBytes = new Uint8Array(await response.arrayBuffer());
  const { Directory } = await loadNativeFileExportModules();
  const targetDirectory = await Directory.pickDirectoryAsync();
  const availableFileName = getAvailableFileName(targetDirectory, targetFileName);
  const targetFile = targetDirectory.createFile(
    availableFileName,
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  );
  targetFile.write(fileBytes);
  return true;
};

const toExcelCellValue = (value: ExcelValue) => {
  if (value instanceof Date) return value;
  if (typeof value === "number") return value;
  if (typeof value === "boolean") return value ? "Yes" : "No";
  if (value === null || value === undefined || value === "") return "-";
  return String(value);
};

export const downloadExcelWorkbook = async <Row,>(options: ExcelTableOptions<Row>) => {
  const handledByBackend = await downloadBackendExcel({
    title: options.title,
    reportKey: options.reportKey,
    generatedAt: options.generatedAt,
    generatedBy: options.generatedBy,
    meta: options.meta,
    fileName: options.fileName,
    columns: options.columns.map((column) => ({
      key: column.key,
      title: column.title,
      width: column.width,
      align: column.align,
    })),
    rows: options.rows.map((row, rowIndex) =>
      Object.fromEntries(options.columns.map((column) => [column.key, column.getValue(row, rowIndex)]))
    ),
  });
  if (handledByBackend) return;

  const ExcelJS = await loadExcelJs();
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "CBS Revora";
  workbook.created = new Date();
  const worksheet = workbook.addWorksheet(options.title.slice(0, 31) || "Report");
  const columns = options.columns || [];
  const columnCount = Math.max(columns.length, 1);

  worksheet.columns = columns.map((column) => ({
    key: column.key,
    width: column.width || 18,
  }));

  const cbsLogoBuffer = await assetToArrayBuffer(CBS_LOGO);
  const revoraLogoBuffer = await assetToArrayBuffer(REVORA_LOGO);
  if (cbsLogoBuffer) {
    const cbsLogoId = workbook.addImage({ buffer: cbsLogoBuffer, extension: "png" });
    worksheet.addImage(cbsLogoId, { tl: { col: 0, row: 0 }, ext: { width: 52, height: 52 } });
  }
  if (revoraLogoBuffer) {
    const revoraLogoId = workbook.addImage({ buffer: revoraLogoBuffer, extension: "png" });
    worksheet.addImage(revoraLogoId, { tl: { col: 1, row: 0.15 }, ext: { width: 190, height: 44 } });
  }

  worksheet.mergeCells(1, Math.max(columnCount - 2, 1), 1, columnCount);
  worksheet.mergeCells(2, Math.max(columnCount - 2, 1), 2, columnCount);
  worksheet.getCell(1, Math.max(columnCount - 2, 1)).value = options.title;
  worksheet.getCell(1, Math.max(columnCount - 2, 1)).font = { bold: true, size: 20, color: { argb: "FF0F2852" } };
  worksheet.getCell(1, Math.max(columnCount - 2, 1)).alignment = { horizontal: "right", vertical: "middle" };
  worksheet.getCell(2, Math.max(columnCount - 2, 1)).value = options.subtitle || "";
  worksheet.getCell(2, Math.max(columnCount - 2, 1)).font = { size: 11, color: { argb: "FF475569" } };
  worksheet.getCell(2, Math.max(columnCount - 2, 1)).alignment = { horizontal: "right", vertical: "middle" };
  worksheet.getRow(1).height = 28;
  worksheet.getRow(2).height = 22;
  worksheet.getRow(3).height = 10;

  const metaItems: ExcelMetaItem[] = [
    ...(!options.meta?.some(m => m.label === "Generated At") ? [{ label: "Generated At", value: formatDateTime(options.generatedAt) }] : []),
    ...(options.generatedBy && !options.meta?.some(m => m.label === "Generated By") ? [{ label: "Generated By", value: options.generatedBy }] : []),
    ...(!options.meta?.some(m => m.label === "Total Rows") ? [{ label: "Total Rows", value: options.rows.length }] : []),
    ...(options.meta || []),
  ];

  let rowIndex = 4;
  metaItems.forEach((item) => {
    worksheet.getCell(rowIndex, 1).value = item.label;
    worksheet.getCell(rowIndex, 1).font = { bold: true, color: { argb: "FF334155" } };
    worksheet.getCell(rowIndex, 1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFEAF0F7" } };
    worksheet.getCell(rowIndex, 2).value = toExcelCellValue(item.value);
    if (columnCount > 2) {
      worksheet.mergeCells(rowIndex, 2, rowIndex, columnCount);
    }
    rowIndex += 1;
  });

  rowIndex += 1;
  const headerRow = worksheet.getRow(rowIndex);
  columns.forEach((column, columnIndex) => {
    const cell = headerRow.getCell(columnIndex + 1);
    cell.value = column.title;
    cell.font = { bold: true, color: { argb: "FF0F172A" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFD9E2F3" } };
    cell.alignment = { horizontal: column.align || "left", vertical: "middle" };
    cell.border = {
      top: { style: "thin", color: { argb: "FFB7C4D4" } },
      left: { style: "thin", color: { argb: "FFB7C4D4" } },
      bottom: { style: "thin", color: { argb: "FFB7C4D4" } },
      right: { style: "thin", color: { argb: "FFB7C4D4" } },
    };
  });

  options.rows.forEach((row, dataIndex) => {
    const excelRow = worksheet.getRow(rowIndex + dataIndex + 1);
    columns.forEach((column, columnIndex) => {
      const rawValue = column.getValue(row, dataIndex);
      const cell = excelRow.getCell(columnIndex + 1);
      cell.value = toExcelCellValue(rawValue);
      cell.alignment = { horizontal: column.align || "left", vertical: "top", wrapText: true };
      if (typeof rawValue === "number") {
        cell.numFmt = "#,##0";
      }
      cell.border = {
        top: { style: "thin", color: { argb: "FFB7C4D4" } },
        left: { style: "thin", color: { argb: "FFB7C4D4" } },
        bottom: { style: "thin", color: { argb: "FFB7C4D4" } },
        right: { style: "thin", color: { argb: "FFB7C4D4" } },
      };
    });
  });

  worksheet.views = [{ state: "frozen", ySplit: rowIndex }];
  const buffer = await workbook.xlsx.writeBuffer();
  downloadWorkbookBuffer(buffer, options.fileName || buildExcelFileName(options.reportKey, options.generatedAt));
};

const addWorkbookHeader = async (
  workbook: any,
  worksheet: any,
  {
    title,
    subtitle,
    columnCount,
    generatedAt,
    generatedBy,
    meta = [],
  }: {
    title: string;
    subtitle?: string;
    columnCount: number;
    generatedAt?: string | Date;
    generatedBy?: string | null;
    meta?: ExcelMetaItem[];
  }
) => {
  const cbsLogoBuffer = await assetToArrayBuffer(CBS_LOGO);
  const revoraLogoBuffer = await assetToArrayBuffer(REVORA_LOGO);
  if (cbsLogoBuffer) {
    const cbsLogoId = workbook.addImage({ buffer: cbsLogoBuffer, extension: "png" });
    worksheet.addImage(cbsLogoId, { tl: { col: 0, row: 0 }, ext: { width: 52, height: 52 } });
  }
  if (revoraLogoBuffer) {
    const revoraLogoId = workbook.addImage({ buffer: revoraLogoBuffer, extension: "png" });
    worksheet.addImage(revoraLogoId, { tl: { col: 1, row: 0.15 }, ext: { width: 190, height: 44 } });
  }

  worksheet.mergeCells(1, Math.max(columnCount - 2, 1), 1, columnCount);
  worksheet.mergeCells(2, Math.max(columnCount - 2, 1), 2, columnCount);
  worksheet.getCell(1, Math.max(columnCount - 2, 1)).value = title;
  worksheet.getCell(1, Math.max(columnCount - 2, 1)).font = { bold: true, size: 20, color: { argb: "FF0F2852" } };
  worksheet.getCell(1, Math.max(columnCount - 2, 1)).alignment = { horizontal: "right", vertical: "middle" };
  worksheet.getCell(2, Math.max(columnCount - 2, 1)).value = subtitle || "";
  worksheet.getCell(2, Math.max(columnCount - 2, 1)).font = { size: 11, color: { argb: "FF475569" } };
  worksheet.getCell(2, Math.max(columnCount - 2, 1)).alignment = { horizontal: "right", vertical: "middle" };
  worksheet.getRow(1).height = 28;
  worksheet.getRow(2).height = 22;
  worksheet.getRow(3).height = 10;

  const metaItems: ExcelMetaItem[] = [
    { label: "Generated At", value: formatDateTime(generatedAt) },
    ...(generatedBy ? [{ label: "Generated By", value: generatedBy }] : []),
    ...meta,
  ];

  let rowIndex = 4;
  metaItems.forEach((item) => {
    worksheet.getCell(rowIndex, 1).value = item.label;
    worksheet.getCell(rowIndex, 1).font = { bold: true, color: { argb: "FF334155" } };
    worksheet.getCell(rowIndex, 1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFEAF0F7" } };
    worksheet.getCell(rowIndex, 2).value = toExcelCellValue(item.value);
    if (columnCount > 2) {
      worksheet.mergeCells(rowIndex, 2, rowIndex, columnCount);
    }
    rowIndex += 1;
  });

  return rowIndex + 1;
};

export const flattenExcelSections = (sections: ExcelSection[]) => {
  const flattenedRows: Record<string, ExcelValue>[] = [];
  const maxColumns = Math.max(1, ...sections.map((section) => section.columns.length));
  const sectionColumns = Array.from({ length: maxColumns }, (_item, index) => ({
    key: `col_${index + 1}`,
    title: index === 0 ? "Section / Data" : "",
    width: 22,
  }));
  
  sections.forEach((section) => {
    flattenedRows.push({ col_1: section.title });
    flattenedRows.push(Object.fromEntries(section.columns.map((column, index) => [`col_${index + 1}`, column.title])));
    if (section.rows.length === 0) {
      flattenedRows.push({ col_1: "No data." });
    } else {
      section.rows.forEach((row) => {
        flattenedRows.push(Object.fromEntries(section.columns.map((column, index) => [`col_${index + 1}`, row[column.key]])));
      });
    }
    flattenedRows.push({});
  });
  
  return { columns: sectionColumns, rows: flattenedRows };
};

export const downloadExcelSectionWorkbook = async (options: ExcelSectionWorkbookOptions) => {
  const { columns: sectionColumns, rows: flattenedRows } = flattenExcelSections(options.sections);
  const handledByBackend = await downloadBackendExcel({
    title: options.title,
    reportKey: options.reportKey,
    generatedAt: options.generatedAt,
    generatedBy: options.generatedBy,
    meta: options.meta,
    fileName: options.fileName,
    columns: sectionColumns,
    rows: flattenedRows,
  });
  if (handledByBackend) return;

  const ExcelJS = await loadExcelJs();
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "CBS Revora";
  workbook.created = new Date();
  const worksheet = workbook.addWorksheet(options.title.slice(0, 31) || "Report");
  const columnCount = Math.max(1, ...options.sections.map((section) => section.columns.length));

  worksheet.columns = Array.from({ length: columnCount }, (_item, index) => ({
    key: `col_${index + 1}`,
    width: 18,
  }));

  let rowIndex = await addWorkbookHeader(workbook, worksheet, {
    title: options.title,
    subtitle: options.subtitle,
    columnCount,
    generatedAt: options.generatedAt,
    generatedBy: options.generatedBy,
    meta: options.meta,
  });

  options.sections.forEach((section) => {
    worksheet.mergeCells(rowIndex, 1, rowIndex, Math.max(section.columns.length, 1));
    const titleCell = worksheet.getCell(rowIndex, 1);
    titleCell.value = section.title;
    titleCell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    titleCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F2852" } };
    titleCell.alignment = { horizontal: "left", vertical: "middle" };
    rowIndex += 1;

    const headerRow = worksheet.getRow(rowIndex);
    section.columns.forEach((column, columnIndex) => {
      const cell = headerRow.getCell(columnIndex + 1);
      cell.value = column.title;
      cell.font = { bold: true, color: { argb: "FF0F172A" } };
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFD9E2F3" } };
      cell.alignment = { horizontal: column.align || "left", vertical: "middle" };
      cell.border = {
        top: { style: "thin", color: { argb: "FFB7C4D4" } },
        left: { style: "thin", color: { argb: "FFB7C4D4" } },
        bottom: { style: "thin", color: { argb: "FFB7C4D4" } },
        right: { style: "thin", color: { argb: "FFB7C4D4" } },
      };
      if (column.width) {
        worksheet.getColumn(columnIndex + 1).width = Math.max(worksheet.getColumn(columnIndex + 1).width || 0, column.width);
      }
    });
    rowIndex += 1;

    section.rows.forEach((row) => {
      const excelRow = worksheet.getRow(rowIndex);
      section.columns.forEach((column, columnIndex) => {
        const rawValue = row[column.key];
        const cell = excelRow.getCell(columnIndex + 1);
        cell.value = toExcelCellValue(rawValue);
        cell.alignment = { horizontal: column.align || "left", vertical: "top", wrapText: true };
        if (typeof rawValue === "number") cell.numFmt = "#,##0";
        cell.border = {
          top: { style: "thin", color: { argb: "FFB7C4D4" } },
          left: { style: "thin", color: { argb: "FFB7C4D4" } },
          bottom: { style: "thin", color: { argb: "FFB7C4D4" } },
          right: { style: "thin", color: { argb: "FFB7C4D4" } },
        };
      });
      rowIndex += 1;
    });

    if (section.rows.length === 0) {
      worksheet.mergeCells(rowIndex, 1, rowIndex, Math.max(section.columns.length, 1));
      worksheet.getCell(rowIndex, 1).value = "No data.";
      worksheet.getCell(rowIndex, 1).font = { color: { argb: "FF64748B" }, italic: true };
      rowIndex += 1;
    }

    rowIndex += 2;
  });

  const buffer = await workbook.xlsx.writeBuffer();
  downloadWorkbookBuffer(buffer, options.fileName || buildExcelFileName(options.reportKey, options.generatedAt));
};
